pipeline {
    agent any
    tools { 
        maven 'maven' 
    }
   
   
     stages {
        stage('Build') {
            steps {
                // Execute build steps here, for example:
                sh 'mvn clean install -f maths/pom.xml'
            }
        }
        
	    stage ('Upload Artifact') {
		    steps {
			    rtUpload (
                    // Obtain an Artifactory server instance, defined in Jenkins --> Manage Jenkins --> Configure System:
                    serverId: 'artifactory', 
                    spec: """{
                            "files": [
                                    {
                                        "pattern": "/var/jenkins_home/workspace/calculate/maths/target/maths-1.3.jar",
                                        "target": "libs-snapshot-local"
                                    }
                                ]
                            }"""
                )
            }
        }
    }
}
